name = "ModelMacro"
uuid = "57a8d7aa-52e8-490b-8f80-6cfcf63f65fa"
authors = ["Ramiro Vignolo <ramirovignolo@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
