name = "ModelMacro"
uuid = "57a8d7aa-52e8-490b-8f80-6cfcf63f65fa"
authors = ["Ramiro Vignolo <ramirovignolo@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
MacroTools = "0.5"
OrderedCollections = "1.3"
Parameters = "0.12"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
